#!/bin/bash
# =============================================================================
#  🔧  RAAGHAS — ENVIRONMENT SETUP WIZARD
#  Run this locally on your Mac ONCE to create all .env.production files
#  Usage: bash setup_env.sh
# =============================================================================
GREEN='\033[0;32m'; CYAN='\033[0;36m'; YELLOW='\033[1;33m'
RED='\033[0;31m'; BOLD='\033[1m'; RESET='\033[0m'

banner() { echo -e "\n${BOLD}${CYAN}══ $* ══${RESET}\n"; }
ask()    { echo -e "${YELLOW}  › $1${RESET}"; }
info()   { echo -e "${CYAN}  $1${RESET}"; }
ok()     { echo -e "${GREEN}  ✓ $1${RESET}"; }

banner "🔧 Raaghas Environment Setup Wizard"

echo ""
info "This wizard creates .env.production files for all 3 apps."
info "Have these values ready:"
echo ""
echo "  1. VPS IP / domains (rc.grafty.pro, admin.rc.grafty.pro, api.rc.grafty.pro)"
echo "  2. Clerk publishable key + secret key"
echo "  3. PostgreSQL DATABASE_URL (from vps_setup.sh output)"
echo "  4. Razorpay key + secret (optional)"
echo "  5. Resend API key (optional)"
echo ""
read -p "Press ENTER to begin..."

# ── Collect shared values ─────────────────────────────────────────────────────
banner "Shared Settings"

ask "Storefront domain? [default: rc.grafty.pro]"
read -r STOREFRONT_DOMAIN
STOREFRONT_DOMAIN=${STOREFRONT_DOMAIN:-rc.grafty.pro}

ask "Admin domain? [default: admin.rc.grafty.pro]"
read -r ADMIN_DOMAIN
ADMIN_DOMAIN=${ADMIN_DOMAIN:-admin.rc.grafty.pro}

ask "API domain? [default: api.rc.grafty.pro]"
read -r API_DOMAIN
API_DOMAIN=${API_DOMAIN:-api.rc.grafty.pro}

# ── Shared Settings ───────────────────────────────────────────────────────────

# ── Database ──────────────────────────────────────────────────────────────────
banner "PostgreSQL Database"
info "Format: postgresql://USER:PASSWORD@localhost:5432/DBNAME"
info "This was printed at the end of vps_setup.sh"

ask "DATABASE_URL:"
read -r DATABASE_URL

# ── Payments ──────────────────────────────────────────────────────────────────
banner "Razorpay (optional — press ENTER to skip)"

ask "RAZORPAY_KEY_ID (rzp_live_...):"
read -r RAZORPAY_KEY_ID

ask "RAZORPAY_KEY_SECRET:"
read -r RAZORPAY_KEY_SECRET

ask "RAZORPAY_WEBHOOK_SECRET:"
read -r RAZORPAY_WEBHOOK_SECRET

# ── Email ─────────────────────────────────────────────────────────────────────
banner "Email / Resend (optional — press ENTER to skip)"

ask "RESEND_API_KEY (re_...):"
read -r RESEND_API_KEY

ask "EMAIL_FROM address [default: noreply@rc.grafty.pro]:"
read -r EMAIL_FROM
EMAIL_FROM=${EMAIL_FROM:-noreply@rc.grafty.pro}

# ── OpenAI ────────────────────────────────────────────────────────────────────
banner "OpenAI (optional — press ENTER to skip)"

ask "OPENAI_API_KEY (sk-...):"
read -r OPENAI_API_KEY

# ── Write .env.production files ───────────────────────────────────────────────
banner "Writing .env.production Files"

# --- Storefront ---
cat > apps/storefront/.env.production <<EOF
# Generated by setup_env.sh — $(date)
NEXT_PUBLIC_APP_URL=https://${STOREFRONT_DOMAIN}
NEXT_PUBLIC_API_URL=https://${API_DOMAIN}

DATABASE_URL=${DATABASE_URL}
EOF
ok "apps/storefront/.env.production written."

# --- Admin ---
cat > apps/admin/.env.production <<EOF
# Generated by setup_env.sh — $(date)
NEXT_PUBLIC_APP_URL=https://${ADMIN_DOMAIN}
NEXT_PUBLIC_API_URL=https://${API_DOMAIN}/api/v1
NEXT_PUBLIC_STOREFRONT_URL=https://${STOREFRONT_DOMAIN}

DATABASE_URL=${DATABASE_URL}
EOF
ok "apps/admin/.env.production written."

# --- API ---
JWT_SECRET=$(openssl rand -base64 48 | tr -d '\n')
cat > apps/api/.env.production <<EOF
# Generated by setup_env.sh — $(date)
PORT=6005
NODE_ENV=production
API_URL=https://${API_DOMAIN}
CORS_ORIGINS=https://${STOREFRONT_DOMAIN},https://${ADMIN_DOMAIN}

DATABASE_URL=${DATABASE_URL}

JWT_SECRET=${JWT_SECRET}

RAZORPAY_KEY_ID=${RAZORPAY_KEY_ID}
RAZORPAY_KEY_SECRET=${RAZORPAY_KEY_SECRET}
RAZORPAY_WEBHOOK_SECRET=${RAZORPAY_WEBHOOK_SECRET}

RESEND_API_KEY=${RESEND_API_KEY}
EMAIL_FROM=${EMAIL_FROM}

OPENAI_API_KEY=${OPENAI_API_KEY}
EOF
ok "apps/api/.env.production written."

# ── Summary ───────────────────────────────────────────────────────────────────
echo ""
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN}  ✅  All .env.production files created!${RESET}"
echo -e "${BOLD}${GREEN}══════════════════════════════════════════${RESET}"
echo ""
echo "  Storefront  → apps/storefront/.env.production"
echo "  Admin       → apps/admin/.env.production"
echo "  API         → apps/api/.env.production"
echo ""
echo -e "${YELLOW}  Next: run ${BOLD}bash deploy.sh${RESET}${YELLOW} to deploy to VPS${RESET}"
echo ""
